<?xml version="1.0" encoding="utf-8"?><Database Name="Regional" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HERETICANTHEM21\SQLEXPRESS;Initial Catalog=Regional;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RegionalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PersonalId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Reservation" Member="Reservations" ThisKey="Id" OtherKey="IdCustomer" Type="Reservation" />
    </Type>
  </Table>
  <Table Name="dbo.State" Member="States">
    <Type Name="State">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="State_Hotel" Member="Hotels" ThisKey="Id" OtherKey="IdState" Type="Hotel" />
    </Type>
  </Table>
  <Table Name="dbo.Hotel" Member="Hotels">
    <Type Name="Hotel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IdState" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanSell" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TripAdvisor" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TripAdvisorEng" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Map" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Hotel_Period" Member="Periods" ThisKey="Id" OtherKey="IdHotel" Type="Period" />
      <Association Name="Hotel_Room" Member="Rooms" ThisKey="Id" OtherKey="IdHotel" Type="Room" />
      <Association Name="Hotel_Service" Member="Services" ThisKey="Id" OtherKey="IdPosada" Type="Service" />
      <Association Name="State_Hotel" Member="State" ThisKey="IdState" OtherKey="Id" Type="State" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentMethod" Member="PaymentMethods">
    <Type Name="PaymentMethod">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="PaymentMethod_ReservationsBuyed" Member="ReservationsBuyeds" ThisKey="Id" OtherKey="IdPaymentMethod" Type="ReservationsBuyed" />
    </Type>
  </Table>
  <Table Name="dbo.Periods" Member="Periods">
    <Type Name="Period">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BeginDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EndDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdHotel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BeginMonth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EndMonth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Hotel_Period" Member="Hotel" ThisKey="IdHotel" OtherKey="Id" Type="Hotel" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Promotion" Member="Promotions">
    <Type Name="Promotion">
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LowSeasonPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="HighSeasonPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="IdRoom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Room_Promotion" Member="Room" ThisKey="IdRoom" OtherKey="Id" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reservation" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="IdCustomer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Arrival" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Departure" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReservationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Adults" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Childrens" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="IdRoom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdReservationStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Agency" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Reservation_ReservationsBuyed" Member="ReservationsBuyeds" ThisKey="Id" OtherKey="IdReservation" Type="ReservationsBuyed" />
      <Association Name="Customer_Reservation" Member="Customer" ThisKey="IdCustomer" OtherKey="Id" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="ReservationStatus_Reservation" Member="ReservationStatus" ThisKey="IdReservationStatus" OtherKey="Id" Type="ReservationStatus" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Room_Reservation" Member="Room" ThisKey="IdRoom" OtherKey="Id" Type="Room" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReservationsBuyed" Member="ReservationsBuyeds">
    <Type Name="ReservationsBuyed">
      <Column Name="IdReservation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPaymentMethod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalPayed" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="PaymentMethod_ReservationsBuyed" Member="PaymentMethod" ThisKey="IdPaymentMethod" OtherKey="Id" Type="PaymentMethod" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Reservation_ReservationsBuyed" Member="Reservation" ThisKey="IdReservation" OtherKey="Id" Type="Reservation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReservationStatus" Member="ReservationStatus">
    <Type Name="ReservationStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ReservationStatus_Reservation" Member="Reservations" ThisKey="Id" OtherKey="IdReservationStatus" Type="Reservation" />
    </Type>
  </Table>
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IdHotel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LowSeasonPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="HighSeasonPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Discount1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Room_Promotion" Member="Promotions" ThisKey="Id" OtherKey="IdRoom" Type="Promotion" />
      <Association Name="Room_Reservation" Member="Reservations" ThisKey="Id" OtherKey="IdRoom" Type="Reservation" />
      <Association Name="Hotel_Room" Member="Hotel" ThisKey="IdHotel" OtherKey="Id" Type="Hotel" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Service" Member="Services">
    <Type Name="Service">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IdPosada" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DurationDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyLater" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Hotel_Service" Member="Hotel" ThisKey="IdPosada" OtherKey="Id" Type="Hotel" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>